[tox]
envlist = py311, py312, lint

[testenv:lint]
basepython = python
deps = flake8
commands = flake8 python_magnetrun tests

[testenv]
deps =
    pytest>=6.2
setenv =
    PYTHONPATH = {toxinidir}
commands = pytest tests/ {posargs}
