"""
VProcess File Reader for LNCMI

This module provides functionality to read VProcess data files generated by
the LNCMI control system. The files have an ASCII header followed by binary data.

VProcess files contain process monitoring data typically sampled at 1 Hz.
Unlike kHz and RMS data which are FEPC-specific, vprocess files contain
general process variables from the control system.

File Structure:
    - ASCII header (8 lines starting with #)
    - Binary data: timestamp (8 bytes) + variables (float32 4 bytes or uint8 1 byte each)
    - Typical: 1 hour of data (~3600 samples)
"""

import logging
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd

from ...utils.validation import validate_vprocess_format
from .._binary_reader_base import ChannelVariable, _BinaryFileReaderBase

logger = logging.getLogger(__name__)

# Backward-compat alias
VProcessVariable = ChannelVariable


def parse_vprocess_filename(filename: str) -> tuple[datetime, datetime] | None:
    """Parse a VProcess filename to extract start and end times.

    Expected format: ``YYYYMMDD_HHMMSS__YYYYMMDD_HHMMSS.vprocess``

    Parameters
    ----------
    filename : str
        VProcess filename (basename only).

    Returns
    -------
    tuple or None
        ``(start_datetime, end_datetime)`` if parsing succeeds, ``None`` otherwise.
    """
    pattern = r"(\d{8})_(\d{6})__(\d{8})_(\d{6})\.vprocess"
    match = re.match(pattern, filename)
    if not match:
        return None
    try:
        start_dt = datetime.strptime(
            f"{match.group(1)}_{match.group(2)}", "%Y%m%d_%H%M%S"
        )
        end_dt = datetime.strptime(
            f"{match.group(3)}_{match.group(4)}", "%Y%m%d_%H%M%S"
        )
        return (start_dt, end_dt)
    except ValueError:
        return None


def find_vprocess_files_for_date(
    directory: str, date: datetime, pattern: str = "*.vprocess"
) -> list[Path]:
    """Find all VProcess files for a specific date.

    Parameters
    ----------
    directory : str
        Directory to search.
    date : datetime
        Date to search for.
    pattern : str, optional
        Glob pattern (default: ``"*.vprocess"``).

    Returns
    -------
    list of Path
        Sorted list of VProcess files for the specified date.
    """
    dir_path = Path(directory)
    return sorted(
        f for f in sorted(dir_path.glob(pattern))
        if (tr := parse_vprocess_filename(f.name)) and tr[0].date() == date.date()
    )


class VProcessFileReader(_BinaryFileReaderBase):
    """Reader for VProcess binary files with ASCII headers."""

    _encoding = "utf-8"

    # ── abstract implementations ──────────────────────────────────────────

    def _validate_format(self) -> None:
        validate_vprocess_format(str(self.filepath))

    def _parse_variables(self, line: str) -> None:
        """Parse the ``# variables = …`` line.

        Parameters
        ----------
        line : str
            Raw header line starting with ``"# variables"``.
        """
        match = re.search(r"# variables\s*=\s*(.+)", line)
        if not match:
            return
        for var_spec in (s.strip() for s in match.group(1).split(";") if s.strip()):
            m = re.match(r"(\w+)\s*\[(.+?)\]", var_spec)
            if not m:
                continue
            props: dict[str, str] = {}
            for prop in m.group(2).split("|"):
                if ":" in prop:
                    k, v = prop.split(":", 1)
                    props[k.strip()] = v.strip()
            self.variables.append(
                ChannelVariable(
                    name=m.group(1),
                    var_type=props.get("type", "float32"),
                    unit=props.get("unit"),
                    min_val=(
                        float(props["min"])
                        if "min" in props and props["min"] != "_"
                        else None
                    ),
                    max_val=(
                        float(props["max"])
                        if "max" in props and props["max"] != "_"
                        else None
                    ),
                    display_format=props.get("df"),
                )
            )
        logger.debug("Parsed %d variables", len(self.variables))

    def _parse_extra_header(self, line: str) -> None:
        if line.startswith("# vprocess data file"):
            self._parse_format(line)

    def _make_timestamps(self, raw: list[float]) -> pd.DatetimeIndex:
        return pd.DatetimeIndex(
            [datetime.fromtimestamp(t, tz=UTC) for t in raw]
        )

    # ── VProcess-specific header method ───────────────────────────────────

    def _parse_format(self, line: str) -> None:
        match = re.search(r"# vprocess data file - (.+)", line)
        if match:
            self.metadata["format"] = match.group(1).strip()


# ── convenience functions ─────────────────────────────────────────────────

def read_vprocess_file(filepath: str, endian: str = "big") -> pd.DataFrame:
    """Read a VProcess file into a :class:`~pandas.DataFrame`.

    Parameters
    ----------
    filepath : str
        Path to the VProcess file.
    endian : str, optional
        Endianness: ``"big"`` (default) or ``"little"``.

    Returns
    -------
    pd.DataFrame
        DataFrame with UTC timestamp index and one column per channel.
    """
    return VProcessFileReader(filepath, endian=endian).read()


def get_vprocess_info(
    filepath: str, endian: str = "big"
) -> tuple[dict[str, Any], pd.DataFrame]:
    """Return metadata and variable information from a VProcess file.

    Parameters
    ----------
    filepath : str
        Path to the VProcess file.
    endian : str, optional
        Endianness: ``"big"`` (default) or ``"little"``.

    Returns
    -------
    tuple
        ``(metadata_dict, variables_dataframe)``.
    """
    reader = VProcessFileReader(filepath, endian=endian)
    reader.parse_header()
    return reader.get_metadata(), reader.get_variable_info()


__all__ = [
    "VProcessFileReader",
    "VProcessVariable",
    "ChannelVariable",
    "read_vprocess_file",
    "get_vprocess_info",
    "parse_vprocess_filename",
    "find_vprocess_files_for_date",
]


def main() -> None:
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Read and display VProcess files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("filepath", help="Path to the VProcess file")
    parser.add_argument(
        "--endian", "-e",
        choices=["big", "little"],
        default="little",
        help="Endianness of binary data (default: little)",
    )
    args = parser.parse_args()

    reader = VProcessFileReader(args.filepath, endian=args.endian)
    reader.print_summary()
    logger.info("Variable Information:\n%s", reader.get_variable_info())
    df = reader.read()
    logger.info("Data shape: %s", df.shape)
    logger.info("First rows:\n%s", df.head())


if __name__ == "__main__":
    main()
