"""
RMS File Reader for FEPC-AUX-LNCMI Format

This module provides functionality to read RMS (Root Mean Square) data files
generated by the LNCMI control system. The files have an ASCII header followed
by binary data.
"""

import logging
import re
from typing import Any

import pandas as pd

from ...utils.validation import validate_rms_format
from .._binary_reader_base import (
    ChannelVariable,
    _BinaryFileReaderBase,
)

logger = logging.getLogger(__name__)

# Kept for backward-compat imports
DEFAULT_SAMPLE_WIDTH = 257
DEFAULT_DATA_OFFSET = 0

# Backward-compat alias
RMSVariable = ChannelVariable


class RMSFileReader(_BinaryFileReaderBase):
    """Reader for RMS binary files with ASCII headers."""

    _encoding = "US-ASCII"
    _default_sample_width = DEFAULT_SAMPLE_WIDTH
    _default_data_offset = DEFAULT_DATA_OFFSET

    # ── abstract implementations ──────────────────────────────────────────

    def _validate_format(self) -> None:
        validate_rms_format(str(self.filepath))

    def _parse_variables(self, line: str) -> None:
        """Parse the ``# variables = …`` line.

        Parameters
        ----------
        line : str
            Raw header line starting with ``"# variables"``.
        """
        match = re.search(r"# variables\s*=\s*(.+)", line)
        if not match:
            return
        for var_def in match.group(1).split(";"):
            var_def = var_def.strip()
            if not var_def:
                continue
            m = re.match(r"(\S+)\s*\[(.+)\]", var_def)
            if not m:
                continue
            name = m.group(1)
            props: dict[str, str] = {}
            for prop in m.group(2).split("|"):
                if ":" in prop:
                    k, v = prop.split(":", 1)
                    props[k.strip()] = v.strip()
            self.variables.append(
                ChannelVariable(
                    name=name,
                    var_type=props.get("type", "unknown"),
                    unit=props.get("unit"),
                    min_val=float(props["min"]) if "min" in props else None,
                    max_val=float(props["max"]) if "max" in props else None,
                    display_format=props.get("df"),
                )
            )

    def _parse_extra_header(self, line: str) -> None:
        if line.startswith("# format"):
            self._parse_format(line)
        elif line.startswith("# processed on"):
            self._parse_processed_info(line)

    def _make_timestamps(self, raw: list[float]) -> pd.DatetimeIndex:
        return pd.to_datetime(raw, unit="s", utc=True)

    # ── RMS-specific header methods ───────────────────────────────────────

    def _parse_format(self, line: str) -> None:
        match = re.search(r"# format\s*=\s*(.+)", line)
        if match:
            self.metadata["format"] = match.group(1).strip()

    def _parse_processed_info(self, line: str) -> None:
        self.metadata["processed_info"] = line[2:].strip()

    # ── variable info with byte_size column ───────────────────────────────

    def get_variable_info(self) -> pd.DataFrame:
        """Return channel metadata including ``byte_size``.

        Returns
        -------
        pd.DataFrame
            Columns: ``name``, ``type``, ``unit``, ``min``, ``max``,
            ``byte_size``, ``display_format``.
        """
        df = super().get_variable_info()
        if self.variables:
            df["byte_size"] = [v.byte_size for v in self.variables]
        return df


# ── convenience functions ─────────────────────────────────────────────────

def read_rms_file(filepath: str, endian: str = "big") -> pd.DataFrame:
    """Read an RMS file and return the data as a :class:`~pandas.DataFrame`.

    Parameters
    ----------
    filepath : str
        Path to the RMS file.
    endian : str, optional
        Endianness: ``"big"`` (default) or ``"little"``.

    Returns
    -------
    pd.DataFrame
        DataFrame with UTC timestamp index and one column per channel.
    """
    return RMSFileReader(filepath, endian=endian).read()


def get_rms_info(
    filepath: str, endian: str = "big"
) -> tuple[dict[str, Any], pd.DataFrame]:
    """Return metadata and variable information from an RMS file.

    Parameters
    ----------
    filepath : str
        Path to the RMS file.
    endian : str, optional
        Endianness: ``"big"`` (default) or ``"little"``.

    Returns
    -------
    tuple
        ``(metadata_dict, variables_dataframe)``.
    """
    reader = RMSFileReader(filepath, endian=endian)
    reader.parse_header()
    return reader.get_metadata(), reader.get_variable_info()


def main() -> None:
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Read and display RMS binary files with ASCII headers",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("filepath", help="Path to the RMS file")
    parser.add_argument(
        "--endian", "-e",
        choices=["big", "little"],
        default="big",
        help="Endianness of binary data (default: big)",
    )
    args = parser.parse_args()

    reader = RMSFileReader(args.filepath, endian=args.endian)
    reader.print_summary()
    logger.info("Variable Information:\n%s", reader.get_variable_info())
    df = reader.read()
    logger.info("Data shape: %s", df.shape)
    logger.info("First rows:\n%s", df.head())


if __name__ == "__main__":
    main()
